services:
  api_contato:
    build: ./contact_service
    ports:
      - "8004:8004"
  
  api_manipulation:
    build: ./manipulation_service
    ports:
      - "8005:8005"
    depends_on:
      - api_contato